import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Crest | Assets",
    // description: "Generated by create next app",
    icons: 'https://ams.crestinfosystems.net/assest-management.ico'
};



export default function Layout({children}: {children: React.ReactNode}) {
    return (
        <section>
            {children}
        </section>
    );
}