import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Crest | Human Resources",
    // description: "Generated by create next app",
    icons: 'https://hrms.crestinfosystems.net/favicon.ico'
};

export default function Layout({children}: {children: React.ReactNode}) {
    return (
        <section>
            {children}
        </section>
    );
}