import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Crest | Time Tracker",
    // description: "Generated by create next app",
    icons: 'https://tms.crestinfosystems.net/logo1.svg'
};

export default function Layout({children}: {children: React.ReactNode}) {
    return (
        <section>
            {children}
        </section>
    );
}