import type { Metadata } from "next";
import "./globals.css";
import { NavBarContextProvider } from "./ui/navBarContext";


export const metadata: Metadata = {
  title: "Crest | Central System",
  // description: "Generated by create next app",
  icons: 'https://central.crestinfosystems.net/favicon.ico'
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-primary-color">
        <NavBarContextProvider>
          {children}
        </NavBarContextProvider>
      </body>
    </html>
  );
}
