import { PageHeaderProvider } from "@/app/ui/hrms/pagetitle.context";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Crest | Human Resources",
    // description: "Generated by create next app",
    icons: 'https://hrms.crestinfosystems.net/favicon.ico'
};

export default function Layout({ children }: { children: React.ReactNode }) {
    return (
        // <div className="mt-20">
        <PageHeaderProvider>
            {children}
        </PageHeaderProvider>
        // </div>
    );
}